=== timurgen/energiforbruk-simulator/trunk/XSDParser/src/simple.xsd
<?xml version="1.0"?>
<!--
Beskriver s책kalt "simple" modell som bruker f책 parametre
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="project">
        <xs:complexType>
            <xs:sequence>
                <!--Descriptione fields of modell-->   
                <xs:element name="description">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="1">
                            <!--first element in each modell is project name-->
                            <xs:element name="project-name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="255" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--next element are name of project creator (user name in our system i think) -->
                            <xs:element name="project-author">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="255" />                            
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!-- element that contains creation date of project -->
                            <xs:element name="project-creation-date">
                                <xs:simpleType>
                                    <xs:restriction base="xs:date">
                                    <!-- //TODO -->   
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--project version, godt 책 tenke p책 ka slags format skal brukes, og skrive da regex i restriksjoner -->
                            <xs:element name="project-version">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="255" />     
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>  
                        </xs:sequence>
                    </xs:complexType>    
                </xs:element>
                <!--Buildings unit-->
                <xs:element name="unit">
                    <xs:complexType>
                        <xs:sequence>
                            <!--mode simple eller advanced -->
                            <xs:element name="mode">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="simple"/>
                                        <xs:enumeration value="advanced"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!--areal av enhet -->
                            <xs:element name="area">
                                <xs:simpleType>
                                    <xs:restriction  base="xs:decimal">
                                        <xs:minInclusive value=""/>
                                        <xs:maxInclusive value="999999.99"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>    
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== timurgen/energiforbruk-simulator/trunk/XSDParser/src/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<project
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='simple.xsd'>
    <description>
        <project-name>Her</project-name>
        <project-author>Suka</project-author>
        <project-creation-date>2002-02-24</project-creation-date>
        <project-version>1.0.0.0</project-version>
    </description>
    <unit>
        <mode>simple</mode>
        <area>5000.0</area>
    </unit>

</project>
