=== timurgen/energiforbruk-simulator/trunk/DOMXMLParserTraining/src/DTDParser/modell.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/modell.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE project SYSTEM "modell.dtd">

    <project>
    ...
    </project>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT project (profile|unit|description)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (project-version|creation-date|project-owner|project-name)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT project-name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT project-owner (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT creation-date (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT project-version (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT unit (class|volume|area)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT area (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT volume (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT class (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT profile EMPTY>

=== timurgen/energiforbruk-simulator/trunk/DOMXMLParserTraining/src/DTDParser/modell.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "modell.dtd">


<project>
    <description>
        <project-name>Test</project-name>
        <project-owner>Timur Samkharadze</project-owner>
        <creation-date>08.09.1983</creation-date>
        <project-version>1.0.0</project-version>
    </description>
    <unit>
        <area>50</area>
        <volume>150</volume>
        <class>TEC-69</class>
    </unit>
    <profile>
    </profile>
</project>
